name: Set up Rocq
description: Install Rocq through opam
author: Tej Chajed

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: package
  color: red

# Define your inputs here.
inputs:
  rocq-version:
    description:
      'The version of Rocq to install (latest, weekly, dev, or full version like
      9.1.0)'
    default: 'latest'
  opam-repositories:
    description: 'Additional opam repositories to add (YAML name:url object)'
    required: false
    default: ''
  cache-key-opam-files:
    description:
      'Opam files to use for cache key. Separate patterns with newlines.'
    required: false
    default: '*.opam'

runs:
  using: node24
  main: dist/index.js
  post: dist/post.js
  post-if: success()
